version: '3'

services:
  laravel-app:
    build: .
    container_name: app_laravel
    ports:
      - "8091:80"
    volumes:
      - ./:/usr/share/nginx/html
      - ./nginx_conf:/etc/nginx/conf.d
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge